// SPDX-License-Identifier: GPL-2.0-only
/* @generated by lkm2 checkpointgen; fixed raw SBI DBCN handler. */
#include <linux/types.h>

#define LKM2_SBI_EXT_DBCN 0x4442434eUL
#define LKM2_SBI_DBCN_WRITE_BYTE 2UL

static void lkm2_cp_write_byte(uint8_t byte)
{
	register unsigned long a0 asm ("a0") = byte;
	register unsigned long a1 asm ("a1") = 0;
	register unsigned long a6 asm ("a6") = LKM2_SBI_DBCN_WRITE_BYTE;
	register unsigned long a7 asm ("a7") = LKM2_SBI_EXT_DBCN;

	asm volatile ("ecall" : "+r" (a0), "+r" (a1), "+r" (a6), "+r" (a7) :: "memory");
}

static void lkm2_cp_write_bytes(const char *bytes)
{
	while (*bytes)
		lkm2_cp_write_byte(*bytes++);
}

static void lkm2_cp_write_hex(uint64_t value)
{
	static const char digits[] = "0123456789abcdef";
	int shift;

	for (shift = 60; shift >= 0; shift -= 4)
		lkm2_cp_write_byte(digits[(value >> shift) & 0xf]);
}

extern void lkm_checkpoint_kernelmap_ready_invariant_kernel_map_established_a95a97317faa0fe4(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3);
extern void lkm_checkpoint_kernelmap_ready_invariant_kernel_map_records_supported_paging_mode_0e608836f90b6692(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3);
extern void lkm_checkpoint_kernelmap_ready_invariant_paging_mode_probe_completed_with_satp_bare_6791f7d466e20943(uint64_t arg0, uint64_t arg1);
extern void lkm_checkpoint_vm_preset_ensures_kernelmap_ready_837d42c0fb0afe2a(void);
extern void lkm_checkpoint_vm_preset_ensures_trampolinepagetable_prepared_65f36136de89b77a(void);
extern void lkm_checkpoint_vm_preset_ensures_earlypagetable_prepared_43327cb7f3a809ec(void);
extern void lkm_checkpoint_vm_prepared_invariant_kernelmap_ready_c18a56ae00a96c36(void);
extern void lkm_checkpoint_vm_prepared_invariant_trampolinepagetable_prepared_64e6d8955ba8c842(void);
extern void lkm_checkpoint_vm_prepared_invariant_earlypagetable_prepared_6097a0585b105e87(void);
extern void lkm_checkpoint_vm_prepared_invariant_kernel_map_established_f792f58326f85c31(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3);
extern void lkm_checkpoint_vm_prepared_invariant_kernel_map_records_supported_paging_mode_c671c012d1e44484(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3);
extern void lkm_checkpoint_vm_prepared_invariant_paging_mode_probe_completed_with_satp_bare_f12f0b1a1339b309(uint64_t arg0, uint64_t arg1);
extern void lkm_checkpoint_trampolinepagetable_ready_invariant_trampoline_first_segment_mapping_established_2e156bd1e813bde5(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5);
extern void lkm_checkpoint_earlypagetable_ready_invariant_early_kernel_image_mapping_established_82f28d771e9bc844(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4);
extern void lkm_checkpoint_earlypagetable_ready_invariant_early_dtb_four_mib_mapping_established_0bbf54bbbcf71183(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5, uint64_t arg6, uint64_t arg7, uint64_t arg8, uint64_t arg9);
extern void lkm_checkpoint_vm_setup_ensures_kernelmap_ready_bc55d479cb51cad1(void);
extern void lkm_checkpoint_vm_setup_ensures_trampolinepagetable_ready_b6c03ff5a27f77f2(void);
extern void lkm_checkpoint_vm_setup_ensures_earlypagetable_ready_182ab94ab6148881(void);
extern void lkm_checkpoint_vm_ready_invariant_kernelmap_ready_d385c290b66fc137(void);
extern void lkm_checkpoint_vm_ready_invariant_trampolinepagetable_ready_19e5e1f6370553b5(void);
extern void lkm_checkpoint_vm_ready_invariant_earlypagetable_ready_b9b913d33ba38a07(void);
extern void lkm_checkpoint_vm_ready_invariant_kernel_map_established_cd9878b93b7a432a(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3);
extern void lkm_checkpoint_vm_ready_invariant_kernel_map_records_supported_paging_mode_62e4c4ed610c4504(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3);
extern void lkm_checkpoint_vm_ready_invariant_paging_mode_probe_completed_with_satp_bare_1e6dbd876ee03897(uint64_t arg0, uint64_t arg1);
extern void lkm_checkpoint_vm_ready_invariant_trampoline_first_segment_mapping_established_f0722558a4ed9154(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5);
extern void lkm_checkpoint_vm_ready_invariant_early_kernel_image_mapping_established_66f281a4a220ed25(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4);
extern void lkm_checkpoint_vm_ready_invariant_early_dtb_four_mib_mapping_established_59d4f121d4813eba(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5, uint64_t arg6, uint64_t arg7, uint64_t arg8, uint64_t arg9);
extern void lkm_checkpoint_vm_ready_invariant_vm_setup_completes_with_satp_bare_baf3733ce308f8ff(uint64_t arg0);

void lkm_checkpoint_kernelmap_ready_invariant_kernel_map_established_a95a97317faa0fe4(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=KernelMap.Ready.Invariant.kernel_map_established hash=a95a97317faa0fe4");
	lkm2_cp_write_bytes(" kernel_va=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" kernel_pa=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" page_offset=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" kernel_va_pa_offset=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_kernelmap_ready_invariant_kernel_map_records_supported_paging_mode_0e608836f90b6692(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=KernelMap.Ready.Invariant.kernel_map_records_supported_paging_mode hash=0e608836f90b6692");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" levels=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" top_shift=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" page_offset=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_kernelmap_ready_invariant_paging_mode_probe_completed_with_satp_bare_6791f7d466e20943(uint64_t arg0, uint64_t arg1)
{
	lkm2_cp_write_bytes("LKMCP1 id=KernelMap.Ready.Invariant.paging_mode_probe_completed_with_satp_bare hash=6791f7d466e20943");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" satp=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_preset_ensures_kernelmap_ready_837d42c0fb0afe2a(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Preset.Ensures.KernelMap.Ready hash=837d42c0fb0afe2a");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_preset_ensures_trampolinepagetable_prepared_65f36136de89b77a(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Preset.Ensures.TrampolinePageTable.Prepared hash=65f36136de89b77a");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_preset_ensures_earlypagetable_prepared_43327cb7f3a809ec(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Preset.Ensures.EarlyPageTable.Prepared hash=43327cb7f3a809ec");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_prepared_invariant_kernelmap_ready_c18a56ae00a96c36(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Prepared.Invariant.KernelMap.Ready hash=c18a56ae00a96c36");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_prepared_invariant_trampolinepagetable_prepared_64e6d8955ba8c842(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Prepared.Invariant.TrampolinePageTable.Prepared hash=64e6d8955ba8c842");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_prepared_invariant_earlypagetable_prepared_6097a0585b105e87(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Prepared.Invariant.EarlyPageTable.Prepared hash=6097a0585b105e87");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_prepared_invariant_kernel_map_established_f792f58326f85c31(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Prepared.Invariant.kernel_map_established hash=f792f58326f85c31");
	lkm2_cp_write_bytes(" kernel_va=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" kernel_pa=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" page_offset=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" kernel_va_pa_offset=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_prepared_invariant_kernel_map_records_supported_paging_mode_c671c012d1e44484(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Prepared.Invariant.kernel_map_records_supported_paging_mode hash=c671c012d1e44484");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" levels=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" top_shift=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" page_offset=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_prepared_invariant_paging_mode_probe_completed_with_satp_bare_f12f0b1a1339b309(uint64_t arg0, uint64_t arg1)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Prepared.Invariant.paging_mode_probe_completed_with_satp_bare hash=f12f0b1a1339b309");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" satp=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_trampolinepagetable_ready_invariant_trampoline_first_segment_mapping_established_2e156bd1e813bde5(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5)
{
	lkm2_cp_write_bytes("LKMCP1 id=TrampolinePageTable.Ready.Invariant.trampoline_first_segment_mapping_established hash=2e156bd1e813bde5");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" va=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" pa=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" size=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_bytes(" flags=0x");
	lkm2_cp_write_hex(arg4);
	lkm2_cp_write_bytes(" path_ok=0x");
	lkm2_cp_write_hex(arg5);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_earlypagetable_ready_invariant_early_kernel_image_mapping_established_82f28d771e9bc844(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4)
{
	lkm2_cp_write_bytes("LKMCP1 id=EarlyPageTable.Ready.Invariant.early_kernel_image_mapping_established hash=82f28d771e9bc844");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" va=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" pa=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" flags=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_bytes(" coverage_ok=0x");
	lkm2_cp_write_hex(arg4);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_earlypagetable_ready_invariant_early_dtb_four_mib_mapping_established_0bbf54bbbcf71183(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5, uint64_t arg6, uint64_t arg7, uint64_t arg8, uint64_t arg9)
{
	lkm2_cp_write_bytes("LKMCP1 id=EarlyPageTable.Ready.Invariant.early_dtb_four_mib_mapping_established hash=0bbf54bbbcf71183");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" dtb_pa=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" dtb_va=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" fix_va=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_bytes(" leaf0_pa=0x");
	lkm2_cp_write_hex(arg4);
	lkm2_cp_write_bytes(" leaf0_flags=0x");
	lkm2_cp_write_hex(arg5);
	lkm2_cp_write_bytes(" leaf1_pa=0x");
	lkm2_cp_write_hex(arg6);
	lkm2_cp_write_bytes(" leaf1_flags=0x");
	lkm2_cp_write_hex(arg7);
	lkm2_cp_write_bytes(" size=0x");
	lkm2_cp_write_hex(arg8);
	lkm2_cp_write_bytes(" coverage_ok=0x");
	lkm2_cp_write_hex(arg9);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_setup_ensures_kernelmap_ready_bc55d479cb51cad1(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Setup.Ensures.KernelMap.Ready hash=bc55d479cb51cad1");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_setup_ensures_trampolinepagetable_ready_b6c03ff5a27f77f2(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Setup.Ensures.TrampolinePageTable.Ready hash=b6c03ff5a27f77f2");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_setup_ensures_earlypagetable_ready_182ab94ab6148881(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Setup.Ensures.EarlyPageTable.Ready hash=182ab94ab6148881");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_kernelmap_ready_d385c290b66fc137(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.KernelMap.Ready hash=d385c290b66fc137");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_trampolinepagetable_ready_19e5e1f6370553b5(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.TrampolinePageTable.Ready hash=19e5e1f6370553b5");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_earlypagetable_ready_b9b913d33ba38a07(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.EarlyPageTable.Ready hash=b9b913d33ba38a07");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_kernel_map_established_cd9878b93b7a432a(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.kernel_map_established hash=cd9878b93b7a432a");
	lkm2_cp_write_bytes(" kernel_va=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" kernel_pa=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" page_offset=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" kernel_va_pa_offset=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_kernel_map_records_supported_paging_mode_62e4c4ed610c4504(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.kernel_map_records_supported_paging_mode hash=62e4c4ed610c4504");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" levels=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" top_shift=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" page_offset=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_paging_mode_probe_completed_with_satp_bare_1e6dbd876ee03897(uint64_t arg0, uint64_t arg1)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.paging_mode_probe_completed_with_satp_bare hash=1e6dbd876ee03897");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" satp=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_trampoline_first_segment_mapping_established_f0722558a4ed9154(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.trampoline_first_segment_mapping_established hash=f0722558a4ed9154");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" va=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" pa=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" size=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_bytes(" flags=0x");
	lkm2_cp_write_hex(arg4);
	lkm2_cp_write_bytes(" path_ok=0x");
	lkm2_cp_write_hex(arg5);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_early_kernel_image_mapping_established_66f281a4a220ed25(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.early_kernel_image_mapping_established hash=66f281a4a220ed25");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" va=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" pa=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" flags=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_bytes(" coverage_ok=0x");
	lkm2_cp_write_hex(arg4);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_early_dtb_four_mib_mapping_established_59d4f121d4813eba(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5, uint64_t arg6, uint64_t arg7, uint64_t arg8, uint64_t arg9)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.early_dtb_four_mib_mapping_established hash=59d4f121d4813eba");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" dtb_pa=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" dtb_va=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" fix_va=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_bytes(" leaf0_pa=0x");
	lkm2_cp_write_hex(arg4);
	lkm2_cp_write_bytes(" leaf0_flags=0x");
	lkm2_cp_write_hex(arg5);
	lkm2_cp_write_bytes(" leaf1_pa=0x");
	lkm2_cp_write_hex(arg6);
	lkm2_cp_write_bytes(" leaf1_flags=0x");
	lkm2_cp_write_hex(arg7);
	lkm2_cp_write_bytes(" size=0x");
	lkm2_cp_write_hex(arg8);
	lkm2_cp_write_bytes(" coverage_ok=0x");
	lkm2_cp_write_hex(arg9);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_vm_setup_completes_with_satp_bare_baf3733ce308f8ff(uint64_t arg0)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.vm_setup_completes_with_satp_bare hash=baf3733ce308f8ff");
	lkm2_cp_write_bytes(" satp=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_swapperpagetable_online_invariant_vm_ready_b73b881b5f980ae3(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=SwapperPageTable.Online.Invariant.Vm.Ready hash=b73b881b5f980ae3");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_swapperpagetable_online_invariant_memblock_online_90bad5fa0e5750ee(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=SwapperPageTable.Online.Invariant.MemBlock.Online hash=90bad5fa0e5750ee");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_swapperpagetable_online_invariant_swapper_fixmap_established_b4e9868ff5db1567(uint64_t arg0, uint64_t arg1)
{
	lkm2_cp_write_bytes("LKMCP1 id=SwapperPageTable.Online.Invariant.swapper_fixmap_established hash=b4e9868ff5db1567");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" fixmap_va=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_swapperpagetable_online_invariant_swapper_linear_map_established_728a216973172b02(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=SwapperPageTable.Online.Invariant.swapper_linear_map_established hash=728a216973172b02");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" linear_va=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" linear_pa=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" linear_flags=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_swapperpagetable_online_invariant_swapper_kernel_map_established_179177a1c0dccae0(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=SwapperPageTable.Online.Invariant.swapper_kernel_map_established hash=179177a1c0dccae0");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" kernel_va=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" kernel_pa=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" kernel_flags=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_swapperpagetable_online_invariant_swapper_fixmap_cleared_9c02b21480ffe619(uint64_t arg0)
{
	lkm2_cp_write_bytes("LKMCP1 id=SwapperPageTable.Online.Invariant.swapper_fixmap_cleared hash=9c02b21480ffe619");
	lkm2_cp_write_bytes(" fixmap_cleared=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_swapperpagetable_online_invariant_swapper_satp_switched_1d8d3a55ec020181(uint64_t arg0, uint64_t arg1)
{
	lkm2_cp_write_bytes("LKMCP1 id=SwapperPageTable.Online.Invariant.swapper_satp_switched hash=1d8d3a55ec020181");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" satp_switched=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_swapperpagetable_online_invariant_swapper_tlb_flush_completed_8981df90abec42b7(uint64_t arg0)
{
	lkm2_cp_write_bytes("LKMCP1 id=SwapperPageTable.Online.Invariant.swapper_tlb_flush_completed hash=8981df90abec42b7");
	lkm2_cp_write_bytes(" tlb_flush_completed=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_swapperpagetable_online_invariant_swapper_late_paging_mode_selected_2d17c470e116aaa3(uint64_t arg0, uint64_t arg1)
{
	lkm2_cp_write_bytes("LKMCP1 id=SwapperPageTable.Online.Invariant.swapper_late_paging_mode_selected hash=2d17c470e116aaa3");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" late_mode_selected=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_memblockmemory_enable_establishes_memblock_memory_derived_from_dtb_2ffc6e5d0fa4b50b(uint64_t arg0, uint64_t arg1)
{
	lkm2_cp_write_bytes("LKMCP1 id=MemBlockMemory.Enable.Establishes.memblock_memory_derived_from_dtb hash=2ffc6e5d0fa4b50b");
	lkm2_cp_write_bytes(" memory_count=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" memory_digest=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_memblockmemory_online_invariant_dtbblob_online_32a85f95a2393857(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=MemBlockMemory.Online.Invariant.DtbBlob.Online hash=32a85f95a2393857");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_memblockmemory_online_invariant_dtb_blob_describes_nonempty_valid_physical_memory_eac36c0e1e722e4f(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=MemBlockMemory.Online.Invariant.dtb_blob_describes_nonempty_valid_physical_memory hash=eac36c0e1e722e4f");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_memblockmemory_online_invariant_memblock_memory_derived_from_dtb_d7631211092b2931(uint64_t arg0, uint64_t arg1)
{
	lkm2_cp_write_bytes("LKMCP1 id=MemBlockMemory.Online.Invariant.memblock_memory_derived_from_dtb hash=d7631211092b2931");
	lkm2_cp_write_bytes(" memory_count=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" memory_digest=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_memblockreserved_enable_establishes_memblock_required_reservations_complete_413cd39d2bed340e(uint64_t arg0, uint64_t arg1)
{
	lkm2_cp_write_bytes("LKMCP1 id=MemBlockReserved.Enable.Establishes.memblock_required_reservations_complete hash=413cd39d2bed340e");
	lkm2_cp_write_bytes(" reserved_count=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" reserved_digest=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_memblockreserved_online_invariant_memblockmemory_online_78c4c05f5ebf8e49(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=MemBlockReserved.Online.Invariant.MemBlockMemory.Online hash=78c4c05f5ebf8e49");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_memblockreserved_online_invariant_dtbblob_online_e26363e7b7b4ecf7(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=MemBlockReserved.Online.Invariant.DtbBlob.Online hash=e26363e7b7b4ecf7");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_memblockreserved_online_invariant_kernelimage_ready_cceee4a5d717d223(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=MemBlockReserved.Online.Invariant.KernelImage.Ready hash=cceee4a5d717d223");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_memblockreserved_online_invariant_dtb_blob_physical_range_valid_69bcc14d86d4f75d(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=MemBlockReserved.Online.Invariant.dtb_blob_physical_range_valid hash=69bcc14d86d4f75d");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_memblockreserved_online_invariant_dtb_blob_reserve_map_and_reserved_memory_valid_097ab61dd5c0fa08(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=MemBlockReserved.Online.Invariant.dtb_blob_reserve_map_and_reserved_memory_valid hash=097ab61dd5c0fa08");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_memblockreserved_online_invariant_memblock_required_reservations_complete_17cdb2182de73382(uint64_t arg0, uint64_t arg1)
{
	lkm2_cp_write_bytes("LKMCP1 id=MemBlockReserved.Online.Invariant.memblock_required_reservations_complete hash=17cdb2182de73382");
	lkm2_cp_write_bytes(" reserved_count=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" reserved_digest=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_memblock_online_invariant_memblockmemory_online_4978f36ab8383c7f(uint64_t arg0, uint64_t arg1)
{
	lkm2_cp_write_bytes("LKMCP1 id=MemBlock.Online.Invariant.MemBlockMemory.Online hash=4978f36ab8383c7f");
	lkm2_cp_write_bytes(" memory_count=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" memory_digest=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_memblock_online_invariant_memblockreserved_online_4d817b61472795cc(uint64_t arg0, uint64_t arg1)
{
	lkm2_cp_write_bytes("LKMCP1 id=MemBlock.Online.Invariant.MemBlockReserved.Online hash=4d817b61472795cc");
	lkm2_cp_write_bytes(" reserved_count=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" reserved_digest=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_byte('\n');
}

void lkm2_checkpoint_memory_range(uint64_t index, uint64_t base, uint64_t end)
{
	lkm2_cp_write_bytes("LKMRNG1 kind=memory index=0x");
	lkm2_cp_write_hex(index);
	lkm2_cp_write_bytes(" base=0x");
	lkm2_cp_write_hex(base);
	lkm2_cp_write_bytes(" end=0x");
	lkm2_cp_write_hex(end);
	lkm2_cp_write_byte('\n');
}

void lkm2_checkpoint_reserved_range(uint64_t index, uint64_t base, uint64_t end)
{
	lkm2_cp_write_bytes("LKMRNG1 kind=reserved index=0x");
	lkm2_cp_write_hex(index);
	lkm2_cp_write_bytes(" base=0x");
	lkm2_cp_write_hex(base);
	lkm2_cp_write_bytes(" end=0x");
	lkm2_cp_write_hex(end);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_swapperpagetable_content_fixmap_1b5e2b9649895da5(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=SwapperPageTable.Content.fixmap hash=1b5e2b9649895da5");
	lkm2_cp_write_bytes(" valid=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" count=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" digest_lo=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" digest_hi=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_swapperpagetable_content_linear_8d9969b8ad2f73e1(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=SwapperPageTable.Content.linear hash=8d9969b8ad2f73e1");
	lkm2_cp_write_bytes(" valid=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" count=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" digest_lo=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" digest_hi=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_swapperpagetable_content_kernel_walk_valid_3eebd41d30f56760(uint64_t arg0)
{
	lkm2_cp_write_bytes("LKMCP1 id=SwapperPageTable.Content.kernel_walk_valid hash=3eebd41d30f56760");
	lkm2_cp_write_bytes(" valid=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_byte('\n');
}

void lkm2_checkpoint_content_chunk(uint64_t class_id, uint64_t chunk,
				   uint64_t count, uint64_t lo, uint64_t hi)
{
	const char *name = class_id == 1 ? "fixmap" :
		(class_id == 2 ? "linear" : "kernel");
	lkm2_cp_write_bytes("LKMPTC1 class="); lkm2_cp_write_bytes(name);
	lkm2_cp_write_bytes(" chunk=0x"); lkm2_cp_write_hex(chunk);
	lkm2_cp_write_bytes(" count=0x"); lkm2_cp_write_hex(count);
	lkm2_cp_write_bytes(" digest_lo=0x"); lkm2_cp_write_hex(lo);
	lkm2_cp_write_bytes(" digest_hi=0x"); lkm2_cp_write_hex(hi);
	lkm2_cp_write_byte('\n');
}

void lkm2_checkpoint_content_item(uint64_t class_id, uint64_t index,
				  uint64_t va, uint64_t pa, uint64_t flags)
{
	const char *name = class_id == 1 ? "fixmap" :
		(class_id == 2 ? "linear" : "kernel");
	lkm2_cp_write_bytes("LKMPTI1 class="); lkm2_cp_write_bytes(name);
	lkm2_cp_write_bytes(" index=0x"); lkm2_cp_write_hex(index);
	lkm2_cp_write_bytes(" va=0x"); lkm2_cp_write_hex(va);
	lkm2_cp_write_bytes(" pa=0x"); lkm2_cp_write_hex(pa);
	lkm2_cp_write_bytes(" flags=0x"); lkm2_cp_write_hex(flags);
	lkm2_cp_write_byte('\n');
}
