// SPDX-License-Identifier: GPL-2.0-only
/* @generated by lkm2 checkpointgen; fixed raw SBI DBCN handler. */
#include <linux/types.h>

#define LKM2_SBI_EXT_DBCN 0x4442434eUL
#define LKM2_SBI_DBCN_WRITE_BYTE 2UL

static void lkm2_cp_write_byte(uint8_t byte)
{
	register unsigned long a0 asm ("a0") = byte;
	register unsigned long a1 asm ("a1") = 0;
	register unsigned long a6 asm ("a6") = LKM2_SBI_DBCN_WRITE_BYTE;
	register unsigned long a7 asm ("a7") = LKM2_SBI_EXT_DBCN;

	asm volatile ("ecall" : "+r" (a0), "+r" (a1), "+r" (a6), "+r" (a7) :: "memory");
}

static void lkm2_cp_write_bytes(const char *bytes)
{
	while (*bytes)
		lkm2_cp_write_byte(*bytes++);
}

static void lkm2_cp_write_hex(uint64_t value)
{
	static const char digits[] = "0123456789abcdef";
	int shift;

	for (shift = 60; shift >= 0; shift -= 4)
		lkm2_cp_write_byte(digits[(value >> shift) & 0xf]);
}

extern void lkm_checkpoint_kernelmap_ready_invariant_kernel_map_established_a95a97317faa0fe4(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3);
extern void lkm_checkpoint_kernelmap_ready_invariant_kernel_map_records_supported_paging_mode_0e608836f90b6692(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3);
extern void lkm_checkpoint_kernelmap_ready_invariant_paging_mode_probe_completed_with_satp_bare_6791f7d466e20943(uint64_t arg0, uint64_t arg1);
extern void lkm_checkpoint_vm_preset_ensures_kernelmap_ready_837d42c0fb0afe2a(void);
extern void lkm_checkpoint_vm_preset_ensures_trampolinepagetable_prepared_65f36136de89b77a(void);
extern void lkm_checkpoint_vm_preset_ensures_earlypagetable_prepared_43327cb7f3a809ec(void);
extern void lkm_checkpoint_vm_prepared_invariant_kernelmap_ready_c18a56ae00a96c36(void);
extern void lkm_checkpoint_vm_prepared_invariant_trampolinepagetable_prepared_64e6d8955ba8c842(void);
extern void lkm_checkpoint_vm_prepared_invariant_earlypagetable_prepared_6097a0585b105e87(void);
extern void lkm_checkpoint_vm_prepared_invariant_kernel_map_established_f792f58326f85c31(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3);
extern void lkm_checkpoint_vm_prepared_invariant_kernel_map_records_supported_paging_mode_c671c012d1e44484(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3);
extern void lkm_checkpoint_vm_prepared_invariant_paging_mode_probe_completed_with_satp_bare_f12f0b1a1339b309(uint64_t arg0, uint64_t arg1);
extern void lkm_checkpoint_trampolinepagetable_ready_invariant_trampoline_first_segment_mapping_established_2e156bd1e813bde5(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5);
extern void lkm_checkpoint_earlypagetable_ready_invariant_early_kernel_image_mapping_established_82f28d771e9bc844(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4);
extern void lkm_checkpoint_earlypagetable_ready_invariant_early_dtb_four_mib_mapping_established_0bbf54bbbcf71183(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5, uint64_t arg6, uint64_t arg7, uint64_t arg8, uint64_t arg9);
extern void lkm_checkpoint_vm_setup_ensures_kernelmap_ready_bc55d479cb51cad1(void);
extern void lkm_checkpoint_vm_setup_ensures_trampolinepagetable_ready_b6c03ff5a27f77f2(void);
extern void lkm_checkpoint_vm_setup_ensures_earlypagetable_ready_182ab94ab6148881(void);
extern void lkm_checkpoint_vm_ready_invariant_kernelmap_ready_d385c290b66fc137(void);
extern void lkm_checkpoint_vm_ready_invariant_trampolinepagetable_ready_19e5e1f6370553b5(void);
extern void lkm_checkpoint_vm_ready_invariant_earlypagetable_ready_b9b913d33ba38a07(void);
extern void lkm_checkpoint_vm_ready_invariant_kernel_map_established_cd9878b93b7a432a(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3);
extern void lkm_checkpoint_vm_ready_invariant_kernel_map_records_supported_paging_mode_62e4c4ed610c4504(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3);
extern void lkm_checkpoint_vm_ready_invariant_paging_mode_probe_completed_with_satp_bare_1e6dbd876ee03897(uint64_t arg0, uint64_t arg1);
extern void lkm_checkpoint_vm_ready_invariant_trampoline_first_segment_mapping_established_f0722558a4ed9154(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5);
extern void lkm_checkpoint_vm_ready_invariant_early_kernel_image_mapping_established_66f281a4a220ed25(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4);
extern void lkm_checkpoint_vm_ready_invariant_early_dtb_four_mib_mapping_established_59d4f121d4813eba(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5, uint64_t arg6, uint64_t arg7, uint64_t arg8, uint64_t arg9);
extern void lkm_checkpoint_vm_ready_invariant_vm_setup_completes_with_satp_bare_baf3733ce308f8ff(uint64_t arg0);

void lkm_checkpoint_kernelmap_ready_invariant_kernel_map_established_a95a97317faa0fe4(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=KernelMap.Ready.Invariant.kernel_map_established hash=a95a97317faa0fe4");
	lkm2_cp_write_bytes(" kernel_va=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" kernel_pa=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" page_offset=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" kernel_va_pa_offset=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_kernelmap_ready_invariant_kernel_map_records_supported_paging_mode_0e608836f90b6692(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=KernelMap.Ready.Invariant.kernel_map_records_supported_paging_mode hash=0e608836f90b6692");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" levels=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" top_shift=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" page_offset=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_kernelmap_ready_invariant_paging_mode_probe_completed_with_satp_bare_6791f7d466e20943(uint64_t arg0, uint64_t arg1)
{
	lkm2_cp_write_bytes("LKMCP1 id=KernelMap.Ready.Invariant.paging_mode_probe_completed_with_satp_bare hash=6791f7d466e20943");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" satp=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_preset_ensures_kernelmap_ready_837d42c0fb0afe2a(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Preset.Ensures.KernelMap.Ready hash=837d42c0fb0afe2a");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_preset_ensures_trampolinepagetable_prepared_65f36136de89b77a(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Preset.Ensures.TrampolinePageTable.Prepared hash=65f36136de89b77a");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_preset_ensures_earlypagetable_prepared_43327cb7f3a809ec(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Preset.Ensures.EarlyPageTable.Prepared hash=43327cb7f3a809ec");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_prepared_invariant_kernelmap_ready_c18a56ae00a96c36(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Prepared.Invariant.KernelMap.Ready hash=c18a56ae00a96c36");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_prepared_invariant_trampolinepagetable_prepared_64e6d8955ba8c842(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Prepared.Invariant.TrampolinePageTable.Prepared hash=64e6d8955ba8c842");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_prepared_invariant_earlypagetable_prepared_6097a0585b105e87(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Prepared.Invariant.EarlyPageTable.Prepared hash=6097a0585b105e87");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_prepared_invariant_kernel_map_established_f792f58326f85c31(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Prepared.Invariant.kernel_map_established hash=f792f58326f85c31");
	lkm2_cp_write_bytes(" kernel_va=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" kernel_pa=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" page_offset=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" kernel_va_pa_offset=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_prepared_invariant_kernel_map_records_supported_paging_mode_c671c012d1e44484(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Prepared.Invariant.kernel_map_records_supported_paging_mode hash=c671c012d1e44484");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" levels=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" top_shift=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" page_offset=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_prepared_invariant_paging_mode_probe_completed_with_satp_bare_f12f0b1a1339b309(uint64_t arg0, uint64_t arg1)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Prepared.Invariant.paging_mode_probe_completed_with_satp_bare hash=f12f0b1a1339b309");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" satp=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_trampolinepagetable_ready_invariant_trampoline_first_segment_mapping_established_2e156bd1e813bde5(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5)
{
	lkm2_cp_write_bytes("LKMCP1 id=TrampolinePageTable.Ready.Invariant.trampoline_first_segment_mapping_established hash=2e156bd1e813bde5");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" va=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" pa=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" size=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_bytes(" flags=0x");
	lkm2_cp_write_hex(arg4);
	lkm2_cp_write_bytes(" path_ok=0x");
	lkm2_cp_write_hex(arg5);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_earlypagetable_ready_invariant_early_kernel_image_mapping_established_82f28d771e9bc844(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4)
{
	lkm2_cp_write_bytes("LKMCP1 id=EarlyPageTable.Ready.Invariant.early_kernel_image_mapping_established hash=82f28d771e9bc844");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" va=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" pa=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" flags=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_bytes(" coverage_ok=0x");
	lkm2_cp_write_hex(arg4);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_earlypagetable_ready_invariant_early_dtb_four_mib_mapping_established_0bbf54bbbcf71183(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5, uint64_t arg6, uint64_t arg7, uint64_t arg8, uint64_t arg9)
{
	lkm2_cp_write_bytes("LKMCP1 id=EarlyPageTable.Ready.Invariant.early_dtb_four_mib_mapping_established hash=0bbf54bbbcf71183");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" dtb_pa=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" dtb_va=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" fix_va=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_bytes(" leaf0_pa=0x");
	lkm2_cp_write_hex(arg4);
	lkm2_cp_write_bytes(" leaf0_flags=0x");
	lkm2_cp_write_hex(arg5);
	lkm2_cp_write_bytes(" leaf1_pa=0x");
	lkm2_cp_write_hex(arg6);
	lkm2_cp_write_bytes(" leaf1_flags=0x");
	lkm2_cp_write_hex(arg7);
	lkm2_cp_write_bytes(" size=0x");
	lkm2_cp_write_hex(arg8);
	lkm2_cp_write_bytes(" coverage_ok=0x");
	lkm2_cp_write_hex(arg9);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_setup_ensures_kernelmap_ready_bc55d479cb51cad1(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Setup.Ensures.KernelMap.Ready hash=bc55d479cb51cad1");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_setup_ensures_trampolinepagetable_ready_b6c03ff5a27f77f2(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Setup.Ensures.TrampolinePageTable.Ready hash=b6c03ff5a27f77f2");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_setup_ensures_earlypagetable_ready_182ab94ab6148881(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Setup.Ensures.EarlyPageTable.Ready hash=182ab94ab6148881");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_kernelmap_ready_d385c290b66fc137(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.KernelMap.Ready hash=d385c290b66fc137");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_trampolinepagetable_ready_19e5e1f6370553b5(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.TrampolinePageTable.Ready hash=19e5e1f6370553b5");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_earlypagetable_ready_b9b913d33ba38a07(void)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.EarlyPageTable.Ready hash=b9b913d33ba38a07");
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_kernel_map_established_cd9878b93b7a432a(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.kernel_map_established hash=cd9878b93b7a432a");
	lkm2_cp_write_bytes(" kernel_va=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" kernel_pa=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" page_offset=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" kernel_va_pa_offset=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_kernel_map_records_supported_paging_mode_62e4c4ed610c4504(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.kernel_map_records_supported_paging_mode hash=62e4c4ed610c4504");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" levels=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" top_shift=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" page_offset=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_paging_mode_probe_completed_with_satp_bare_1e6dbd876ee03897(uint64_t arg0, uint64_t arg1)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.paging_mode_probe_completed_with_satp_bare hash=1e6dbd876ee03897");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" satp=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_trampoline_first_segment_mapping_established_f0722558a4ed9154(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.trampoline_first_segment_mapping_established hash=f0722558a4ed9154");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" va=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" pa=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" size=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_bytes(" flags=0x");
	lkm2_cp_write_hex(arg4);
	lkm2_cp_write_bytes(" path_ok=0x");
	lkm2_cp_write_hex(arg5);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_early_kernel_image_mapping_established_66f281a4a220ed25(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.early_kernel_image_mapping_established hash=66f281a4a220ed25");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" va=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" pa=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" flags=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_bytes(" coverage_ok=0x");
	lkm2_cp_write_hex(arg4);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_early_dtb_four_mib_mapping_established_59d4f121d4813eba(uint64_t arg0, uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5, uint64_t arg6, uint64_t arg7, uint64_t arg8, uint64_t arg9)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.early_dtb_four_mib_mapping_established hash=59d4f121d4813eba");
	lkm2_cp_write_bytes(" mode=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_bytes(" dtb_pa=0x");
	lkm2_cp_write_hex(arg1);
	lkm2_cp_write_bytes(" dtb_va=0x");
	lkm2_cp_write_hex(arg2);
	lkm2_cp_write_bytes(" fix_va=0x");
	lkm2_cp_write_hex(arg3);
	lkm2_cp_write_bytes(" leaf0_pa=0x");
	lkm2_cp_write_hex(arg4);
	lkm2_cp_write_bytes(" leaf0_flags=0x");
	lkm2_cp_write_hex(arg5);
	lkm2_cp_write_bytes(" leaf1_pa=0x");
	lkm2_cp_write_hex(arg6);
	lkm2_cp_write_bytes(" leaf1_flags=0x");
	lkm2_cp_write_hex(arg7);
	lkm2_cp_write_bytes(" size=0x");
	lkm2_cp_write_hex(arg8);
	lkm2_cp_write_bytes(" coverage_ok=0x");
	lkm2_cp_write_hex(arg9);
	lkm2_cp_write_byte('\n');
}

void lkm_checkpoint_vm_ready_invariant_vm_setup_completes_with_satp_bare_baf3733ce308f8ff(uint64_t arg0)
{
	lkm2_cp_write_bytes("LKMCP1 id=Vm.Ready.Invariant.vm_setup_completes_with_satp_bare hash=baf3733ce308f8ff");
	lkm2_cp_write_bytes(" satp=0x");
	lkm2_cp_write_hex(arg0);
	lkm2_cp_write_byte('\n');
}
