/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef _LINUX_LKM_CHECKPOINTS_H
#define _LINUX_LKM_CHECKPOINTS_H

#define LKM_CHECKPOINT_BUFFER_CAPACITY 64

#define LKM_CHECKPOINT_ENTRY_PRELUDE_PHASE_STARTED 1
#define LKM_CHECKPOINT_TRAMPOLINE_VM_ONLINE 2
#define LKM_CHECKPOINT_KERNEL_IMAGE_ONLINE 3
#define LKM_CHECKPOINT_EARLY_VM_ONLINE 4
#define LKM_CHECKPOINT_EVENT_STREAM_READY 5
#define LKM_CHECKPOINT_EXCEPTION_STREAM_READY 6
#define LKM_CHECKPOINT_EVENT_STREAM_PREPARED 7
#define LKM_CHECKPOINT_EXCEPTION_STREAM_PREPARED 8
#define LKM_CHECKPOINT_ENTRY_PRELUDE_PHASE_READY 9

#ifndef __ASSEMBLY__
void lkm_checkpoints_dump(void);
#endif

#endif /* _LINUX_LKM_CHECKPOINTS_H */
