/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef _LINUX_LKM_CHECKPOINTS_H
#define _LINUX_LKM_CHECKPOINTS_H

#define LKM_CHECKPOINT_BUFFER_CAPACITY 512
#define LKM_SCHED_CHECKPOINT_BUFFER_CAPACITY 128

#define LKM_SCHED_STAGE_ENTRY 1
#define LKM_SCHED_STAGE_PREPARE_PREV 2
#define LKM_SCHED_STAGE_PICK_NEXT 3
#define LKM_SCHED_STAGE_SWITCH_ENTRY 4
#define LKM_SCHED_STAGE_FINISH_RETURN 5

#define LKM_SCHED_FLAG_PREEMPT 0x01
#define LKM_SCHED_FLAG_SIGNAL_RECOVERED 0x02
#define LKM_SCHED_FLAG_BLOCKED 0x04

#define LKM_SCHED_CLASS_NONE 0
#define LKM_SCHED_CLASS_STOP 1
#define LKM_SCHED_CLASS_DEADLINE 2
#define LKM_SCHED_CLASS_REALTIME 3
#define LKM_SCHED_CLASS_FAIR 4
#define LKM_SCHED_CLASS_IDLE 5
#define LKM_SCHED_CLASS_EXT 6

#define LKM_SCHED_MODE_UNAVAILABLE (-128)

#define LKM_CHECKPOINT_KERNEL_STARTED 1
#define LKM_CHECKPOINT_BOOT_INIT_FLOW_STARTED 2
#define LKM_CHECKPOINT_BOOT_INIT_FLOW_PREPARED 3
#define LKM_CHECKPOINT_TRAP_TYPE_PREPARED 4
#define LKM_CHECKPOINT_EXCEPTION_TYPE_PREPARED 5
#define LKM_CHECKPOINT_TRAMPOLINE_VM_TAKE_OVER 6
#define LKM_CHECKPOINT_RAW_DTB_PREPARED 7
#define LKM_CHECKPOINT_RAW_DTB_READY 8
#define LKM_CHECKPOINT_EARLY_VM_READY 9
#define LKM_CHECKPOINT_EARLY_VM_TAKE_OVER 10
#define LKM_CHECKPOINT_KERNEL_IMAGE_ONLINE 11
#define LKM_CHECKPOINT_TRAP_TYPE_READY 12
#define LKM_CHECKPOINT_CORE_PREPARE_PHASE_STARTED 13
#define LKM_CHECKPOINT_CORE_PREPARE_PHASE_READY 14
#define LKM_CHECKPOINT_EXCEPTION_TYPE_READY 15
#define LKM_CHECKPOINT_MM_CORE_INIT_PHASE_STARTED 16
#define LKM_CHECKPOINT_MM_CORE_INIT_PHASE_READY 17
#define LKM_CHECKPOINT_SCHED_INIT_PHASE_STARTED 18
#define LKM_CHECKPOINT_SCHED_INIT_PHASE_READY 19
#define LKM_CHECKPOINT_IRQ_TIME_INIT_PHASE_STARTED 20
#define LKM_CHECKPOINT_LOCAL_IRQ_ENABLE_PHASE_STARTED 21
#define LKM_CHECKPOINT_LOCAL_IRQ_ENABLE_PHASE_READY 22
#define LKM_CHECKPOINT_PROCESS_PREPARE_PHASE_STARTED 23
#define LKM_CHECKPOINT_BOOT_INIT_REST_INIT_PHASE_READY 24
#define LKM_CHECKPOINT_PRE_SMP_INIT_PHASE_STARTED 25
#define LKM_CHECKPOINT_SMP_BRINGUP_PHASE_STARTED 26
#define LKM_CHECKPOINT_SMP_BRINGUP_PHASE_READY 27
#define LKM_CHECKPOINT_CPU_START_PROVIDER_READY 28
#define LKM_CHECKPOINT_CPU_START_PROVIDER_BOOT_DATA_SELECTED 29
#define LKM_CHECKPOINT_CPU_START_PROVIDER_BOOT_DATA_PUBLISHED 30
#define LKM_CHECKPOINT_CPU_START_PROVIDER_HSM_START_ISSUED 31
#define LKM_CHECKPOINT_AP_ENTRY_PRELUDE_PHASE_STARTED 32
#define LKM_CHECKPOINT_AP_ENTRY_PRELUDE_CURRENT_STACK_ESTABLISHED 33
#define LKM_CHECKPOINT_AP_ENTRY_PRELUDE_PHASE_READY 34
#define LKM_CHECKPOINT_AP_SMP_CALLIN_PHASE_STARTED 35
#define LKM_CHECKPOINT_AP_SMP_CALLIN_CPU_RUNNING_PRODUCED 36
#define LKM_CHECKPOINT_AP_SMP_CALLIN_PHASE_READY 37
#define LKM_CHECKPOINT_AP_ONLINE_IDLE_PHASE_STARTED 38
#define LKM_CHECKPOINT_AP_ONLINE_IDLE_DONE_UP_PRODUCED 39
#define LKM_CHECKPOINT_AP_ONLINE_IDLE_PHASE_READY 40
#define LKM_CHECKPOINT_SECONDARY_CPU_STARTUP_ACK_READY 41
#define LKM_CHECKPOINT_SECONDARY_CPU_ONLINE_ACK_READY 42
#define LKM_CHECKPOINT_RUNTIME_CORE_PHASE_STARTED 43
#define LKM_CHECKPOINT_SCHEDULER_SMP_READY 44
#define LKM_CHECKPOINT_WORKQUEUE_TOPOLOGY_READY 45
#define LKM_CHECKPOINT_ASYNC_CORE_DEFERRED_READY 46
#define LKM_CHECKPOINT_PADATA_CORE_DEFERRED_READY 47
#define LKM_CHECKPOINT_PAGE_ALLOCATOR_LATE_READY 48
#define LKM_CHECKPOINT_RUNTIME_CORE_BOUNDARY_READY 49
#define LKM_CHECKPOINT_INITCALL_PHASE_STARTED 50
#define LKM_CHECKPOINT_INITCALL_PHASE_READY 51
#define LKM_CHECKPOINT_CPUSET_SMP_TRIMMED_READY 52
#define LKM_CHECKPOINT_DRIVER_CORE_DEFERRED_READY 53
#define LKM_CHECKPOINT_IRQ_PROC_VIEW_DEFERRED_READY 54
#define LKM_CHECKPOINT_CTOR_TABLE_READY 55
#define LKM_CHECKPOINT_INITCALL_TABLE_READY 56
#define LKM_CHECKPOINT_INITCALL_BOUNDARY_READY 57
#define LKM_CHECKPOINT_ROOTFS_PHASE_STARTED 58
#define LKM_CHECKPOINT_ROOTFS_PHASE_READY 59
#define LKM_CHECKPOINT_KUNIT_RUNTIME_TRIMMED_READY 60
#define LKM_CHECKPOINT_INITRAMFS_SYNC_DEFERRED_READY 61
#define LKM_CHECKPOINT_ROOTFS_CONSOLE_DEFERRED_READY 62
#define LKM_CHECKPOINT_RAMDISK_EXECUTE_COMMAND_EACCESS_CHECKPOINT 63
#define LKM_CHECKPOINT_ROOT_FSONLINE 64
#define LKM_CHECKPOINT_INTEGRITY_KEYS_DEFERRED_READY 65
#define LKM_CHECKPOINT_ROOTFS_BOUNDARY_READY 66
#define LKM_CHECKPOINT_FINALIZE_PHASE_STARTED 67
#define LKM_CHECKPOINT_FINALIZE_PHASE_READY 68
#define LKM_CHECKPOINT_ASYNC_FULL_SYNC_DEFERRED_READY 69
#define LKM_CHECKPOINT_SYSTEM_STATE_FREEING_INITMEM_CHECKPOINT 70
#define LKM_CHECKPOINT_INIT_MEMORY_CLEANUP_DEFERRED_READY 71
#define LKM_CHECKPOINT_KERNEL_MAPPING_PROTECTION_DEFERRED_READY 72
#define LKM_CHECKPOINT_PTI_FINALIZE_TRIMMED_READY 73
#define LKM_CHECKPOINT_SYSTEM_STATE_ONLINE 74
#define LKM_CHECKPOINT_RCU_INKERNEL_BOOT_ENDED 75
#define LKM_CHECKPOINT_RCU_BOOT_END_READY 76
#define LKM_CHECKPOINT_SYSCTL_ARGS_DEFERRED_READY 77
#define LKM_CHECKPOINT_USER_BOOT_MAIN_ELF_READY 78
#define LKM_CHECKPOINT_USER_BOOT_INTERPRETER_READY 79
#define LKM_CHECKPOINT_USER_BOOT_ADDRESS_SPACE_SETUP_START 80
#define LKM_CHECKPOINT_USER_APP_FLOW_ENTER_USER_MODE 81
#define LKM_CHECKPOINT_USER_ADDRESS_SPACE_READY 82
#define LKM_CHECKPOINT_SYSCALL_TABLE_EXECVE_ARGS_READY 83
#define LKM_CHECKPOINT_USER_EXEC_MAIN_ELF_READY 84
#define LKM_CHECKPOINT_USER_EXEC_INTERPRETER_READY 85
#define LKM_CHECKPOINT_USER_EXEC_TRAP_FRAME_READY 86
#define LKM_CHECKPOINT_USER_EXEC_SATP_READY 87
#define LKM_CHECKPOINT_USER_EXEC_CONTEXT_REPLACED 88
#define LKM_CHECKPOINT_USER_EXEC_SATP_SWITCHED 89
#define LKM_CHECKPOINT_USER_EXEC_RETURN_FRAME_READY 90
#define LKM_CHECKPOINT_SYSCALL_TABLE_OPEN_AT 91
#define LKM_CHECKPOINT_SYSCALL_TABLE_READ 92
#define LKM_CHECKPOINT_SYSCALL_TABLE_WRITE 93
#define LKM_CHECKPOINT_SYSCALL_TABLE_WRITEV 94
#define LKM_CHECKPOINT_SYSCALL_TABLE_CLOSE 95
#define LKM_CHECKPOINT_SYSCALL_TABLE_NEW_FSTAT_AT 96
#define LKM_CHECKPOINT_SYSCALL_TABLE_SET_TID_ADDRESS 97
#define LKM_CHECKPOINT_SYSCALL_TABLE_CLONE 98
#define LKM_CHECKPOINT_SYSCALL_TABLE_WAIT4 99
#define LKM_CHECKPOINT_USER_CHILD_PARENT_WAIT_RESUMED 100
#define LKM_CHECKPOINT_SYSCALL_TABLE_EXIT 101
#define LKM_CHECKPOINT_PAYLOAD_PREPARE_PHASE_ONLINE 102
#define LKM_CHECKPOINT_KERNEL_INIT_FLOW_PAYLOAD_HANDOFF_COMMITTED 103

#ifndef __ASSEMBLY__
#include <linux/types.h>

#define LKM_CHECKPOINT_EXEC_OWNER_NONE 0
#define LKM_CHECKPOINT_EXEC_OWNER_BOOT 1
#define LKM_CHECKPOINT_EXEC_OWNER_RUNTIME 2

#if defined(CONFIG_LKM_CHECKPOINTS) && defined(CONFIG_RISCV)
void lkm_checkpoint_record(u8 id);
void lkm_checkpoint_exec_begin_boot(void);
void lkm_checkpoint_exec_begin_runtime(void);
void lkm_checkpoint_exec_failed(void);
void lkm_checkpoint_record_exec_main_elf_ready(void);
void lkm_checkpoint_record_exec_interpreter_ready(void);
void lkm_checkpoint_record_exec_address_space_setup_start(void);
void lkm_checkpoint_record_exec_satp_ready(void);
void lkm_checkpoint_record_exec_context_replaced(void);
void lkm_checkpoint_record_exec_trap_frame_ready(void);
void lkm_checkpoint_record_exec_return_to_user(void);
void lkm_sched_checkpoint_record(u8 stage, u16 cpu, s8 mode,
				 s32 prev_pid, s32 next_pid,
				 unsigned long prev_state, u8 prev_on_rq,
				 u8 flags, u8 next_class);
#else
static inline void lkm_checkpoint_record(u8 id) {}
static inline void lkm_checkpoint_exec_begin_boot(void) {}
static inline void lkm_checkpoint_exec_begin_runtime(void) {}
static inline void lkm_checkpoint_exec_failed(void) {}
static inline void lkm_checkpoint_record_exec_main_elf_ready(void) {}
static inline void lkm_checkpoint_record_exec_interpreter_ready(void) {}
static inline void lkm_checkpoint_record_exec_address_space_setup_start(void) {}
static inline void lkm_checkpoint_record_exec_satp_ready(void) {}
static inline void lkm_checkpoint_record_exec_context_replaced(void) {}
static inline void lkm_checkpoint_record_exec_trap_frame_ready(void) {}
static inline void lkm_checkpoint_record_exec_return_to_user(void) {}
static inline void lkm_sched_checkpoint_record(u8 stage, u16 cpu, s8 mode,
					       s32 prev_pid, s32 next_pid,
					       unsigned long prev_state,
					       u8 prev_on_rq, u8 flags,
					       u8 next_class) {}
#endif

static inline int lkm_checkpoint_record_payload_handoff_committed(int ret)
{
	if (!ret)
		lkm_checkpoint_record(LKM_CHECKPOINT_KERNEL_INIT_FLOW_PAYLOAD_HANDOFF_COMMITTED);
	return ret;
}

void lkm_checkpoints_dump(void);
#endif

#endif /* _LINUX_LKM_CHECKPOINTS_H */
